version: "3.8"
services: 
  db:
    image: postgres:latest
    container_name: 'digital-bank-db'
    ports: 
      - '5432:5432'
    restart: always
    environment: 
      POSTGRES_USER: 'postgres'
      POSTGRES_PASWORD: '123'
      POSTGRES_DB: 'digital-bank'
      POSTGRES_HOST_AUTH_METHOD: "trust"
    networks: 
      - digitalbank-net
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/database.sql:/docker-entrypoint-initdb.d/database.sql
  
  web:
    build: .
    container_name: 'digital-bank'
    ports: 
      - "5000:5000"
    depends_on: 
      - db
    networks: 
      - digitalbank-net

networks: 
  digitalbank-net:
    driver: bridge
